### ISSUE TITLE
Hugging Chat doesnt work in flathub version

### ISSUE THREAD

**Issue by yarik303** [Bavarder/Bavarder#18]
Cant provide screenshot yet.

Well when i switch to hugging chat and press send it spins forever

maybe its because hugging face got another model.
i hope i post the issue in right one
anyway the os is linux mint 21.1 vera

**Comment by yarik303** [comment]
just forgot to check
LOGS
Exception in thread Thread-1 (thread_run):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/share/bavarder/bavarder/main.py", line 247, in thread_run
    response = self.ask(self.prompt)
  File "/app/share/bavarder/bavarder/main.py", line 231, in ask
    return self.providers[self.provider].ask(prompt)
  File "/app/share/bavarder/bavarder/provider/huggingchat.py", line 27, in ask
    for i in response:
  File "/app/lib/python3.10/site-packages/hgchat/__init__.py", line 37, in ask
    self.get_chat()
  File "/app/lib/python3.10/site-packages/hgchat/__init__.py", line 25, in get_chat
    self.chat = self.new_chat()
  File "/app/lib/python3.10/site-packages/hgchat/__init__.py", line 31, in new_chat
    raise Exception("Failed to create new conversation")
Exception: Failed to create new conversation

**Comment by 0xMRTT** [comment]
This has been fixed in 0.1.4

**Comment by 0xMRTT** [comment]
And fixed in 0.1.5 because a similar issue happened again
