### ISSUE TITLE
AttributeError when using DialoGPT

### ISSUE THREAD

**Issue by wsdmatty** [Bavarder/Bavarder#32]
```
Exception in thread Thread-8 (thread_run):
Traceback (most recent call last):
File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
self.run()
File "/usr/share/bavarder/bavarder/main.py", line 67, in __run
self.__run_backup()
File "/usr/lib/python3.11/threading.py", line 975, in run
self._target(*self._args, **self._kwargs)
File "/usr/share/bavarder/bavarder/main.py", line 1160, in thread_run
response = self.providers[self.provider].ask(self.prompt)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/share/bavarder/bavarder/provider/hfdialogpt.py", line 30, in ask
if self.authorization:
^^^^^^^^^^^^^^^^^^
AttributeError: 'HuggingFaceDialoGPTLargeProvider' object has no attribute 'authorization'

```

**To Reproduce**
1. Select DialoGPT from providers
2. Send Any Message

```
io.github.Bavarder.Bavarder 0.2.3
Environment: KDE
Gtk: 4.10.3
Python: 3.11.3
OS: Linux 6.3.5-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Tue, 30 May 2023 13:43:47 +0000
Providers: ['alpacalora', 'baichat', 'catgpt', 'hfdialogpt', 'hfgoogleflant5xxl', 'hfgoogleflanu12', 'hfgpt2', 'hfgpt2large', 'hfopenassistantsft1pythia12b', 'huggingchat', 'openaigpt35turbo', 'local', 'openaicustom', 'openaigpt4', 'openaitextdavinci003']
Use Theme: True
Use Text View: True
Clear After Send: False
Close All Without Dialog: False
Current Provider: hfdialogpt
```

**Comment by 0xMRTT** [comment]
Shit, I missed to update to the new base class...

**Comment by 0xMRTT** [comment]
Will be fixed in the next release!
